#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

volumes:
  pgdata:
  walletstore:

networks:
  basic:

services:
  ca.foxconn.com.br:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.foxconn.com.br
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.foxconn.com.br-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/41f6db9459771a0c84505a4353108713edfa046f97c81df4be04c35f66ee75ef_sk
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.foxconn.com.br/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca.foxconn.com.br
    networks:
      - basic

  orderer.foxconn.com.br:
    container_name: orderer.foxconn.com.br
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/foxconn.com.br/orderers/orderer.foxconn.com.br/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.foxconn.com.br/peers/peer0.org1.foxconn.com.br/:/etc/hyperledger/msp/peerOrg1
    networks:
      - basic

  peer0.org1.foxconn.com.br:
    container_name: peer0.org1.foxconn.com.br
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.foxconn.com.br:7051
      - CORE_PEER_ID=peer0.org1.foxconn.com.br
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.foxconn.com.br:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
   # command: peer node start
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.foxconn.com.br/peers/peer0.org1.foxconn.com.br/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.foxconn.com.br/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.foxconn.com.br
      - couchdb
    networks:
      - basic

#  peer1.org1.foxconn.com.br:
#    container_name: peer1.org1.foxconn.com.br
#    image: hyperledger/fabric-peer:$IMAGE_TAG
#    environment:
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.foxconn.com.br:7055
#      - CORE_PEER_ID=peer1.org1.foxconn.com.br
#      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
#      - FABRIC_LOGGING_SPEC=info
#      - CORE_CHAINCODE_LOGGING_LEVEL=info
#      - CORE_PEER_LOCALMSPID=Org1MSP
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
#      - CORE_PEER_ADDRESS=peer1.org1.foxconn.com.br:7055
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
#      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
#      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
#      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
#      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
   # command: peer node start
#    command: peer node start --peer-chaincodedev=true
#    ports:
#      - 7055:7055
#      - 7052:7052
#      - 7053:7053
#    volumes:
#        - /var/run/:/host/var/run/
#        - ./crypto-config/peerOrganizations/org1.foxconn.com.br/peers/peer1.org1.foxconn.com.br/msp:/etc/hyperledger/msp/peer
#        - ./crypto-config/peerOrganizations/org1.foxconn.com.br/users:/etc/hyperledger/msp/users
#        - ./config:/etc/hyperledger/configtx
#    networks:
#      - basic

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_ADDRESS=peer0.org1.foxconn.com.br:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foxconn.com.br/users/Admin@org1.foxconn.com.br/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
    #depends_on:
    #  - orderer.foxconn.com.br
    #  - peer0.org1.foxconn.com.br
    #  - couchdb

  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli2
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4
      - CORE_PEER_ADDRESS=peer1.org1.foxconn.com.br:7055
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.foxconn.com.br/users/Admin@org1.foxconn.com.br/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic

  explorerdb.foxconn.com.br:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.foxconn.com.br
    hostname: explorerdb.foxconn.com.br
    environment:
     - DATABASE_DATABASE=fabricexplorer
     - DATABASE_USERNAME=hppoc
     - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - basic

  explorer.foxconn.com.br:
    image: hyperledger/explorer:latest
    container_name: explorer.foxconn.com.br
    hostname: explorer.foxconn.com.br
    environment:
      - DATABASE_HOST=explorerdb.foxconn.com.br
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=true
      - PORT=${PORT:-8080}
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
      - ./crypto-config:/etc/data
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    depends_on:
      explorerdb.foxconn.com.br:
        condition: service_healthy
    networks:
        - basic
